version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/rest"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/recommendation"
    schedule:
      interval: "weekly"
