name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  gravitalia:
    name: Publish Gravitalia
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build the Docker image
      run: |
            docker build . --tag ghcr.io/gravitalia/rest:latest
            docker push ghcr.io/gravitalia/rest:latest
          
  recommendation:
    name: Publish Recommendation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build the Docker image
      run: |
            docker build . --tag ghcr.io/gravitalia/recommendation:latest
            docker push ghcr.io/gravitalia/recommendation:latest
