# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    strategy:
      matrix:
        dir: ["./rest", "./recommendation"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20

    - name: Build
      working-directory: ${{ matrix.dir }}
      run: go build -v ./...

    - name: Test
      working-directory: ${{ matrix.dir }}
      run: go test -v ./...
