name: Rust

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        dir: ["./search", "./recommendation"]
    runs-on: ubuntu-latest
    name: Build
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up cargo cache
      uses: actions/cache@v3
      continue-on-error: false
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: linux-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: linux-cargo
        
    - name: Build
      working-directory: ${{ matrix.dir }}
      run: cargo build
      
    - name: Test
      working-directory: ${{ matrix.dir }}
      run: cargo test
